module.exports = {
  theme: {
    screens: {
      sm: { max: '825px' }, // mobile
      md: { max: '1279px' }, // tablet
      lg: { min: '1280px' }, // desktop
      print: { raw: 'print' },
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',

      muted: 'rgba(19, 15, 33, 0.6)',
      'muted-light': 'rgba(255, 255, 255, 0.5)',

      'darken-50': 'rgba(19, 15, 33, 0.075)',
      'darken-100': 'rgba(19, 15, 33, 0.15)',
      'darken-200': 'rgba(19, 15, 33, 0.2)',
      'darken-300': 'rgba(19, 15, 33, 0.3)',
      darken: 'rgba(19, 15, 33, 0.5)',
      'darken-500': 'rgba(19, 15, 33, 0.7)',
      'darken-600': 'rgba(19, 15, 33, 0.8)',
      'darken-700': 'rgba(19, 15, 33, 0.9)',

      'lighten-50': 'rgba(255, 255, 255, 0.075)',
      'lighten-100': 'rgba(255, 255, 255, 0.15)',
      'lighten-200': 'rgba(255, 255, 255, 0.2)',
      'lighten-300': 'rgba(255, 255, 255, 0.3)',
      lighten: 'rgba(255, 255, 255, 0.5)',
      'lighten-500': 'rgba(255, 255, 255, 0.7)',
      'lighten-600': 'rgba(255, 255, 255, 0.8)',
      'lighten-700': 'rgba(255, 255, 255, 0.9)',

      transparent: 'transparent',

      // primary = alias of blue
      'primary-darkest': '#12283a',
      'primary-darker': '#1c3d5a',
      'primary-dark': '#1478CA',
      primary: '#3B99FC',
      'primary-light': '#6cb2eb',
      'primary-lighter': '#bcdefa',
      'primary-lightest': '#eff8ff',

      // secondary = alias of green
      'secondary-darkest': '#0f2f21',
      'secondary-darker': '#1a4731',
      'secondary-dark': '#1f9d55',
      secondary: '#38c172',
      'secondary-light': '#50D67F',
      'secondary-lighter': '#a2f5bf',
      'secondary-lightest': '#e3fcec',

      // accent = alias of purple
      'accent-darkest': '#360A40',
      'accent-darker': '#66107A',
      'accent-dark': '#9C1FB8',
      accent: '#BB27DD',
      'accent-light': '#C166D5',
      'accent-lighter': '#CC97D9',
      'accent-lightest': '#F3D7FA',

      // active = alias of blue
      'active-darkest': '#12283a',
      'active-darker': '#1c3d5a',
      'active-dark': '#1478CA',
      active: '#3B99FC',
      'active-light': '#6cb2eb',
      'active-lighter': '#bcdefa',
      'active-lightest': '#eff8ff',

      // negative = alias of red
      'negative-darkest': '#3b0d0c',
      'negative-darker': '#621b18',
      'negative-dark': '#cc1f1a',
      negative: '#e3342f',
      'negative-light': '#ef5753',
      'negative-lighter': '#f9acaa',
      'negative-lightest': '#fcebea',

      // warning = alias of orange
      'warning-darkest': '#462a16',
      'warning-darker': '#613b1f',
      'warning-dark': '#de751f',
      warning: '#f6993f',
      'warning-light': '#faad63',
      'warning-lighter': '#fcd9b6',
      'warning-lightest': '#fff5eb',

      // positive = alias of green
      'positive-darkest': '#0f2f21',
      'positive-darker': '#1a4731',
      'positive-dark': '#1f9d55',
      positive: '#38c172',
      'positive-light': '#50D67F',
      'positive-lighter': '#a2f5bf',
      'positive-lightest': '#e3fcec',

      black: '#0e0b2a',
      'grey-darkest': '#3D4852',
      'grey-darker': '#606f7b',
      'grey-dark': '#8795a1',
      grey: '#b8c2cc',
      'grey-light': '#dae1e7',
      'grey-lighter': '#f1f5f8',
      'grey-lightest': '#F5F7F9',
      white: '#ffffff',

      'red-darkest': '#3b0d0c',
      'red-darker': '#621b18',
      'red-dark': '#cc1f1a',
      red: '#e3342f',
      'red-light': '#ef5753',
      'red-lighter': '#f9acaa',
      'red-lightest': '#fcebea',

      'orange-darkest': '#462a16',
      'orange-darker': '#613b1f',
      'orange-dark': '#de751f',
      orange: '#f6993f',
      'orange-light': '#faad63',
      'orange-lighter': '#fcd9b6',
      'orange-lightest': '#fff5eb',

      'yellow-darkest': '#453411',
      'yellow-darker': '#684f1d',
      'yellow-dark': '#f2d024',
      yellow: '#FFC100',
      'yellow-light': '#fff382',
      'yellow-lighter': '#fff9c2',
      'yellow-lightest': '#fcfbeb',

      'green-darkest': '#0f2f21',
      'green-darker': '#1a4731',
      'green-dark': '#1f9d55',
      green: '#48bb78',
      'green-light': '#50D67F',
      'green-lighter': '#a2f5bf',
      'green-lightest': '#e3fcec',

      'blue-darkest': '#12283a',
      'blue-darker': '#1c3d5a',
      'blue-dark': '#1478CA',
      blue: '#3490dc',
      'blue-light': '#6cb2eb',
      'blue-lighter': '#bcdefa',
      'blue-lightest': '#eff8ff',

      'blue2-darkest': '#0E305F',
      'blue2-darker': '#17447C',
      'blue2-dark': '#0E59AA',
      blue2: '#0b6fcc',
      'blue2-light': '#008eff',
      'blue2-lighter': '#42adf0',
      'blue2-lightest': '#92cbec',

      'indigo-darkest': '#191e38',
      'indigo-darker': '#2f365f',
      'indigo-dark': '#5661b3',
      indigo: '#6574cd',
      'indigo-light': '#7886d7',
      'indigo-lighter': '#b2b7ff',
      'indigo-lightest': '#e6e8ff',

      'purple-darkest': '#360A40',
      'purple-darker': '#66107A',
      'purple-dark': '#9C1FB8',
      purple: '#BB27DD',
      'purple-light': '#C166D5',
      'purple-lighter': '#CC97D9',
      'purple-lightest': '#F3D7FA',

      'gold-darkest': '#CC7722',
      'gold-darker': '#FDA50F',
      'gold-dark': '#DAA520',
      gold: '#F9A602',
      'gold-light': '#FFC30B',
      'gold-lighter': '#FADA5E',
      'gold-lightest': '#FCF4A3',

      'lavender-darkest': '#44337A',
      'lavender-darker': '#553C9A',
      'lavender-dark': '#805AD5',
      lavender: '#9F7AEA',
      'lavender-light': '#B794F4',
      'lavender-lighter': '#D6BCFA',
      'lavender-lightest': '#E9D8FD',
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1/2': '2px',
      '1': '4px',
      '2': '6px',
      '3': '10px',
      '4': '13px',
      '5': '16px',
      '6': '20px',
      '8': '26px',
      '10': '32px',
      '12': '3rem',
      '14': '3.5rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '28': '7rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '64': '16rem',
      '80': '20rem',
      '96': '24rem',
      '128': '32rem',
      '192': '46rem',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors.grey-light', 'currentColor'),
    }),
    borderRadius: {
      default: '1px',
      none: '0',
      sm: '1px',
      md: '2px',
      lg: '4px',
      xl: '6px',
      full: '9999px',
    },
    boxShadow: {
      default: '0px 1px 2px rgba(0, 0, 0, 0.25)',
      md: '0px 2px 6px rgba(0, 0, 0, .2)',
      lg: '0px 4px 12px rgba(0, 0, 0, .14)',
      'md-intense': '0px 2px 5px rgba(0, 0, 0, 0.4)',
      'lg-intense': '0px 4px 8px rgba(0, 0, 0, 0.35)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      'inner-intense': 'inset 0 -10px 20px rgba(0, 0, 0, .95)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },
    container: {
      center: true,
      padding: '30px',
    },
    fontFamily: {
      sans: [
        'Inter',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
    },
    fontSize: {
      xs: '9px',
      sm: '11px',
      base: '13px',
      lg: '16px',
      xl: '20px',
      '2xl': '1.5rem', // 24px
      '3xl': '1.875rem', // 30px
      '4xl': '2.25rem', // 36px
      '5xl': '2.75rem', // 48px
      '6xl': '3.5rem', // 54px
      '8xl': '6rem',
    },
    fontWeight: {
      default: 400,
      // hairline: 100,
      // thin: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900,
    },
    opacity: {
      '0': '0',
      '07': '.07',
      '15': '.15',
      '25': '.25',
      '40': '.4',
      '50': '.5',
      '60': '.6',
      '75': '.75',
      '85': '.85',
      '93': '.93',
      '100': '1',
    },
    maxWidth: {
      xs: '20rem',
      sm: '30rem',
      md: '40rem',
      lg: '50rem',
      xl: '60rem',
      '2xl': '70rem',
      '3xl': '80rem',
      '4xl': '90rem',
      '5xl': '100rem',
      full: '100%',
    },
    zIndex: {
      auto: 'auto',
      '-1': -1,
      '0': 0,
      '1': 1,
      '5': 5,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
    },
  },
  variants: {
    accessibility: [],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ['group-hover', 'hover', 'focus'],
    backgroundOpacity: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['group-hover', 'hover', 'focus'],
    borderOpacity: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: ['hover'],
    boxSizing: [],
    cursor: [],
    display: ['responsive'],
    divideColor: [],
    divideOpacity: [],
    divideWidth: [],
    fill: [],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    clear: ['responsive'],
    fontFamily: [],
    fontSize: ['responsive'],
    fontSmoothing: [],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: [],
    lineHeight: ['responsive'],
    listStylePosition: [],
    listStyleType: [],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: [],
    objectPosition: [],
    opacity: ['hover', 'focus'],
    order: [],
    outline: [],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: [],
    placeholderOpacity: [],
    pointerEvents: [],
    position: ['responsive'],
    resize: [],
    space: ['responsive'],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: ['responsive'],
    textColor: ['group-hover', 'hover', 'focus'],
    textOpacity: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: ['responsive'],
    whitespace: [],
    width: ['responsive'],
    wordBreak: [],
    zIndex: ['responsive', 'hover'],
    gap: [],
    gridAutoFlow: [],
    gridTemplateColumns: [],
    gridColumn: [],
    gridColumnStart: [],
    gridColumnEnd: [],
    gridTemplateRows: [],
    gridRow: [],
    gridRowStart: [],
    gridRowEnd: [],
    transform: [],
    transformOrigin: [],
    scale: [],
    rotate: [],
    translate: [],
    skew: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    transitionDuration: [],
    transitionDelay: [],
  },
  corePlugins: {},
  plugins: [],
};
