export default {
  label: 'Forms',
  label_singular: 'Form',
  name: 'form',
  folder: 'netlify/forms',
  create: true,
  delete: true,
  slug: '{{slug}}',
  extension: 'yaml',
  fields: [
    {
      label: 'Tags',
      name: 'tags',
      widget: 'list',
      required: false,
      field: { label: 'tag', name: 'tag', widget: 'string', required: false },
    },
    {
      name: 'path',
      label: 'URL Path',
      widget: 'string',
    },
    {
      name: 'title',
      label: 'title',
      widget: 'string',
    },
    {
      label: 'Title Image',
      name: 'titleImage',
      widget: 'image',
      required: false,
    },
    {
      name: 'subtitle',
      label: 'subtitle',
      widget: 'string',
    },

    {
      label: 'Color',
      name: 'color',
      widget: 'string',
      default: 'black',
    },
    {
      name: 'hubspot',
      label: 'HubSpot',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'formId',
          label: 'HubSpot Form ID',
          widget: 'string',
          required: false,
        },
        {
          name: 'portalId',
          label: 'HubSpot ID',
          widget: 'string',
          required: false,
        },
        {
          name: 'title',
          label: 'Title',
          widget: 'string',
          required: false,
        },
        {
          name: 'description',
          label: 'Description',
          widget: 'string',
          required: false,
        },
      ],
    },
    {
      label: 'Left Content',
      name: 'leftContent',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'title',
          widget: 'markdown',
          required: false,
        },
        {
          name: 'description',
          widget: 'markdown',
          required: false,
        },
      ],
    },
    {
      name: 'collage',
      label: 'Collage',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'title',
          widget: 'string',
          required: false,
        },
        {
          name: 'description',
          widget: 'markdown',
          required: false,
        },
        {
          name: 'images',
          label: 'Images',
          widget: 'list',
          fields: [
            {
              label: 'Image',
              name: 'src',
              widget: 'image',
            },
            {
              label: 'alt',
              name: 'alt',
              widget: 'string',
            },
          ],
        },
        {
          name: 'cta',
          label: 'Call to action',
          widget: 'object',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              hint: 'Leave blank to hide',
              required: false,
            },
            {
              label: 'Color',
              name: 'color',
              widget: 'string',
              default: 'black',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              default: 'https://next.stoplight.io',
              hint: 'Default: https://next.stoplight.io',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
            },
            {
              name: 'download',
              label: 'Download File',
              widget: 'string',
              required: false,
              hint: 'URL to file to download',
            },
            {
              name: 'type',
              label: 'Type',
              widget: 'select',
              options: ['link', 'video', 'submit'],
              default: 'link',
              required: false,
            },
            {
              name: 'submit',
              label: 'Submit',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'button',
                  label: 'Button',
                  widget: 'object',
                  fields: [
                    {
                      name: 'href',
                      label: 'Link',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: false,
                    },
                    {
                      label: 'Color',
                      name: 'color',
                      widget: 'string',
                      default: 'purple',
                      hint: 'Default: purple',
                      required: false,
                    },
                    {
                      name: 'outlined',
                      label: 'Outlined?',
                      widget: 'boolean',
                      required: false,
                    },
                    {
                      name: 'icon',
                      label: 'Icon',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'select',
                      options: ['link', 'video'],
                      default: 'link',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'input',
                  label: 'Input',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'email',
                      required: false,
                    },
                    {
                      name: 'placeholder',
                      label: 'Placeholder',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'formId',
                  label: 'Hubspot FormId',
                  widget: 'string',
                  required: false,
                },
              ],
            },
            {
              name: 'outlined',
              label: 'Outlined?',
              widget: 'boolean',
              required: false,
            },
          ],
        },
      ],
    },
    {
      name: 'testimonials',
      label: 'Testimonial Section',
      widget: 'object',
      required: false,
      fields: [
        {
          fields: [
            {
              name: 'title',
              widget: 'string',
              required: false,
            },
            {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: false,
            },
            {
              name: 'cta',
              label: 'Call to action',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  hint: 'Leave blank to hide',
                  required: false,
                },
                {
                  label: 'Color',
                  name: 'color',
                  widget: 'string',
                  default: 'black',
                  required: false,
                },
                {
                  name: 'href',
                  label: 'Link',
                  widget: 'string',
                  default: 'https://next.stoplight.io',
                  hint: 'Default: https://next.stoplight.io',
                  required: false,
                },
                {
                  name: 'icon',
                  label: 'Icon',
                  widget: 'string',
                  required: false,
                },
                {
                  name: 'download',
                  label: 'Download File',
                  widget: 'string',
                  required: false,
                  hint: 'URL to file to download',
                },
                {
                  name: 'type',
                  label: 'Type',
                  widget: 'select',
                  options: ['link', 'video', 'submit'],
                  default: 'link',
                  required: false,
                },
                {
                  name: 'submit',
                  label: 'Submit',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'button',
                      label: 'Button',
                      widget: 'object',
                      fields: [
                        {
                          name: 'href',
                          label: 'Link',
                          widget: 'string',
                          required: false,
                        },
                        {
                          name: 'title',
                          label: 'Title',
                          widget: 'string',
                          required: false,
                        },
                        {
                          label: 'Color',
                          name: 'color',
                          widget: 'string',
                          default: 'purple',
                          hint: 'Default: purple',
                          required: false,
                        },
                        {
                          name: 'outlined',
                          label: 'Outlined?',
                          widget: 'boolean',
                          required: false,
                        },
                        {
                          name: 'icon',
                          label: 'Icon',
                          widget: 'string',
                          required: false,
                        },
                        {
                          name: 'type',
                          label: 'Type',
                          widget: 'select',
                          options: ['link', 'video'],
                          default: 'link',
                          required: false,
                        },
                      ],
                    },
                    {
                      name: 'input',
                      label: 'Input',
                      widget: 'object',
                      required: false,
                      fields: [
                        {
                          name: 'type',
                          label: 'Type',
                          widget: 'string',
                          default: 'email',
                          required: false,
                        },
                        {
                          name: 'placeholder',
                          label: 'Placeholder',
                          widget: 'string',
                          required: false,
                        },
                      ],
                    },
                    {
                      name: 'formId',
                      label: 'Hubspot FormId',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'outlined',
                  label: 'Outlined?',
                  widget: 'boolean',
                  required: false,
                },
              ],
            },
          ],
        },
        {
          name: 'testimonials',
          label: 'Testimonials',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'image',
              label: 'image',
              widget: 'image',
            },
            {
              name: 'quote',
              label: 'quote',
              widget: 'string',
            },
            {
              name: 'author',
              label: 'author',
              widget: 'string',
            },
            {
              name: 'company',
              label: 'company',
              widget: 'string',
            },
            {
              name: 'role',
              label: 'role',
              widget: 'string',
            },
          ],
        },
        {
          name: 'cta',
          label: 'Call to action',
          widget: 'object',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              hint: 'Leave blank to hide',
              required: false,
            },
            {
              label: 'Color',
              name: 'color',
              widget: 'string',
              default: 'black',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              default: 'https://next.stoplight.io',
              hint: 'Default: https://next.stoplight.io',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
            },
            {
              name: 'download',
              label: 'Download File',
              widget: 'string',
              required: false,
              hint: 'URL to file to download',
            },
            {
              name: 'type',
              label: 'Type',
              widget: 'select',
              options: ['link', 'video', 'submit'],
              default: 'link',
              required: false,
            },
            {
              name: 'submit',
              label: 'Submit',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'button',
                  label: 'Button',
                  widget: 'object',
                  fields: [
                    {
                      name: 'href',
                      label: 'Link',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: false,
                    },
                    {
                      label: 'Color',
                      name: 'color',
                      widget: 'string',
                      default: 'purple',
                      hint: 'Default: purple',
                      required: false,
                    },
                    {
                      name: 'outlined',
                      label: 'Outlined?',
                      widget: 'boolean',
                      required: false,
                    },
                    {
                      name: 'icon',
                      label: 'Icon',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'select',
                      options: ['link', 'video'],
                      default: 'link',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'input',
                  label: 'Input',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'email',
                      required: false,
                    },
                    {
                      name: 'placeholder',
                      label: 'Placeholder',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'formId',
                  label: 'Hubspot FormId',
                  widget: 'string',
                  required: false,
                },
              ],
            },
            {
              name: 'outlined',
              label: 'Outlined?',
              widget: 'boolean',
              required: false,
            },
          ],
        },
      ],
    },
    {
      name: 'actionBar',
      label: 'Action Bar',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'ctas',
          label: 'CTAs',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              required: false,
            },
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              required: false,
            },
          ],
        },
        {
          name: 'enabled',
          label: 'Enabled',
          widget: 'boolean',
          required: false,
        },
        {
          name: 'text',
          label: 'Text',
          widget: 'string',
          required: false,
        },
      ],
    },
    {
      label: 'Tags',
      name: 'tags',
      widget: 'list',
      required: false,
      field: { label: 'tag', name: 'tag', widget: 'string', required: false },
    },
    {
      label: 'Related Tags',
      name: 'relatedTags',
      widget: 'list',
      required: false,
      field: { label: 'tag', name: 'tag', widget: 'string', required: false },
    },
    {
      label: 'Meta Tags',
      name: 'meta',
      widget: 'object',
      required: false,
      hint: 'Defaults to the meta tags defined in Site Settings',
      fields: [
        {
          label: 'Favicon',
          name: 'favicon',
          widget: 'image',
          required: false,
        },
        {
          name: 'title',
          label: 'Site Name',
          widget: 'string',
          required: false,
        },
        {
          label: 'description',
          name: 'description',
          widget: 'string',
          required: false,
        },
        {
          label: 'URL',
          name: 'url',
          widget: 'string',
          required: false,
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
        },
        {
          label: 'Robots',
          name: 'robots',
          widget: 'string',
          default: 'index, follow',
          required: false,
        },
        {
          label: 'Canonical',
          name: 'canonical',
          widget: 'string',
          required: false,
        },
        {
          label: 'Twitter',
          name: 'twitter',
          widget: 'object',
          required: false,
          fields: [
            {
              label: 'Title',
              name: 'title',
              widget: 'string',
              required: false,
            },
            {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: false,
            },
            {
              label: 'Image',
              name: 'image',
              widget: 'image',
              required: false,
            },
            {
              label: 'Username',
              name: 'username',
              widget: 'string',
              required: false,
            },
          ],
        },
      ],
    },
  ],
};
