export default {
  name: 'demoForm',
  label: 'Demo Form',
  file: 'netlify/demo-form',
  fields: [
    {
      name: 'hero',
      label: 'Hero',
      widget: 'object',
      fields: [
        {
          name: 'title',
          label: 'Title',
          widget: 'string',
          default: 'title',
        },
        {
          name: 'subtitle',
          label: 'Subtitle',
          widget: 'string',
          default: 'subtitle',
        },
        {
          name: 'pageName',
          label: 'Page Name',
          widget: 'string',
          required: false,
          hint: 'Small, muted text above the title.',
        },
        {
          name: 'aligned',
          label: 'Alignment',
          widget: 'select',
          options: ['center', 'left', 'right'],
          default: 'center',
          required: false,
          hint: 'Default: center',
        },
        {
          name: 'ctas',
          label: 'Call To Actions',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              hint: 'Leave blank to hide',
              required: false,
            },
            {
              label: 'Color',
              name: 'color',
              widget: 'string',
              default: 'black',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              default: 'https://next.stoplight.io',
              hint: 'Default: https://next.stoplight.io',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
            },
            {
              name: 'download',
              label: 'Download File',
              widget: 'string',
              required: false,
              hint: 'URL to file to download',
            },
            {
              name: 'type',
              label: 'Type',
              widget: 'select',
              options: ['link', 'video', 'submit'],
              default: 'link',
              required: false,
            },
            {
              name: 'submit',
              label: 'Submit',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'button',
                  label: 'Button',
                  widget: 'object',
                  fields: [
                    {
                      name: 'href',
                      label: 'Link',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: false,
                    },
                    {
                      label: 'Color',
                      name: 'color',
                      widget: 'string',
                      default: 'purple',
                      hint: 'Default: purple',
                      required: false,
                    },
                    {
                      name: 'outlined',
                      label: 'Outlined?',
                      widget: 'boolean',
                      required: false,
                    },
                    {
                      name: 'icon',
                      label: 'Icon',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'select',
                      options: ['link', 'video'],
                      default: 'link',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'input',
                  label: 'Input',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'email',
                      required: false,
                    },
                    {
                      name: 'placeholder',
                      label: 'Placeholder',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'formId',
                  label: 'Hubspot FormId',
                  widget: 'string',
                  required: false,
                },
              ],
            },
            {
              name: 'outlined',
              label: 'Outlined?',
              widget: 'boolean',
              required: false,
            },
          ],
        },
        {
          name: 'bgColor',
          label: 'Background Color',
          widget: 'string',
          default: 'black',
          hint: 'Default: black',
          required: false,
        },
        {
          name: 'skew',
          label: 'Skew?',
          widget: 'select',
          options: [
            { label: 'slant left', value: '-3deg' },
            { label: 'steeper slant left', value: '-7deg' },
            { label: 'slant right', value: '3deg' },
            { label: 'steeper slant right', value: '7deg' },
            { label: 'rounded', value: 'rounded' },
          ],
          required: false,
        },
        {
          name: 'particles',
          label: 'Show particles?',
          widget: 'boolean',
          required: false,
        },
        {
          name: 'buttons',
          label: 'Buttons',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              default: 'title',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
              hint: 'Must be a fontawesome icon like check-circle',
            },
          ],
        },
        {
          name: 'cards',
          label: 'Cards',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              default: 'Title',
            },
            {
              name: 'subtitle',
              label: 'Subtitle',
              widget: 'string',
              default: 'subtitle',
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
            },
            {
              name: 'bgColor',
              label: 'Background Color',
              widget: 'string',
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'style',
                  label: 'Style',
                  widget: 'string',
                },
                {
                  name: 'name',
                  label: 'Name',
                  widget: 'string',
                },
              ],
            },
          ],
        },
        {
          name: 'image',
          label: 'Image',
          widget: 'object',
          required: false,
          fields: [
            {
              name: 'src',
              widget: 'image',
              required: false,
            },
            {
              name: 'alt',
              widget: 'string',
              required: false,
            },
            {
              name: 'video',
              label: 'Video URL',
              widget: 'string',
              required: false,
            },
          ],
        },
      ],
    },
    {
      name: 'hubspot',
      label: 'HubSpot',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'formId',
          label: 'HubSpot Form ID',
          widget: 'string',
          required: false,
        },
        {
          name: 'portalId',
          label: 'HubSpot ID',
          widget: 'string',
          required: false,
        },
        {
          name: 'title',
          label: 'Title',
          widget: 'string',
          required: false,
        },
        {
          name: 'description',
          label: 'Description',
          widget: 'string',
          required: false,
        },
      ],
    },

    {
      name: 'features',
      label: 'Features',
      widget: 'list',
      required: false,
      fields: [
        {
          name: 'name',
          label: 'Name',
          widget: 'string',
          required: false,
        },
        {
          name: 'summary',
          label: 'Summary',
          widget: 'string',
          required: false,
        },
        {
          name: 'icon',
          label: 'Icon',
          widget: 'string',
          required: false,
        },
        {
          name: 'iconStyle',
          label: 'Icon Style',
          widget: 'string',
          required: false,
        },
      ],
    },
    {
      name: 'collage',
      label: 'Collage',
      widget: 'object',
      required: false,
      fields: [
        {
          name: 'title',
          widget: 'string',
          required: false,
        },
        {
          name: 'description',
          widget: 'markdown',
          required: false,
        },
        {
          name: 'images',
          label: 'Images',
          widget: 'list',
          fields: [
            {
              label: 'Image',
              name: 'src',
              widget: 'image',
            },
            {
              label: 'alt',
              name: 'alt',
              widget: 'string',
            },
          ],
        },
        {
          name: 'cta',
          label: 'Call to action',
          widget: 'object',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              hint: 'Leave blank to hide',
              required: false,
            },
            {
              label: 'Color',
              name: 'color',
              widget: 'string',
              default: 'black',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              default: 'https://next.stoplight.io',
              hint: 'Default: https://next.stoplight.io',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
            },
            {
              name: 'download',
              label: 'Download File',
              widget: 'string',
              required: false,
              hint: 'URL to file to download',
            },
            {
              name: 'type',
              label: 'Type',
              widget: 'select',
              options: ['link', 'video', 'submit'],
              default: 'link',
              required: false,
            },
            {
              name: 'submit',
              label: 'Submit',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'button',
                  label: 'Button',
                  widget: 'object',
                  fields: [
                    {
                      name: 'href',
                      label: 'Link',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: false,
                    },
                    {
                      label: 'Color',
                      name: 'color',
                      widget: 'string',
                      default: 'purple',
                      hint: 'Default: purple',
                      required: false,
                    },
                    {
                      name: 'outlined',
                      label: 'Outlined?',
                      widget: 'boolean',
                      required: false,
                    },
                    {
                      name: 'icon',
                      label: 'Icon',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'select',
                      options: ['link', 'video'],
                      default: 'link',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'input',
                  label: 'Input',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'email',
                      required: false,
                    },
                    {
                      name: 'placeholder',
                      label: 'Placeholder',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'formId',
                  label: 'Hubspot FormId',
                  widget: 'string',
                  required: false,
                },
              ],
            },
            {
              name: 'outlined',
              label: 'Outlined?',
              widget: 'boolean',
              required: false,
            },
          ],
        },
      ],
    },
    {
      name: 'testimonials',
      label: 'Testimonial Section',
      widget: 'object',
      required: false,
      fields: [
        {
          fields: [
            {
              name: 'title',
              widget: 'string',
              required: false,
            },
            {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: false,
            },
            {
              name: 'cta',
              label: 'Call to action',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  hint: 'Leave blank to hide',
                  required: false,
                },
                {
                  label: 'Color',
                  name: 'color',
                  widget: 'string',
                  default: 'black',
                  required: false,
                },
                {
                  name: 'href',
                  label: 'Link',
                  widget: 'string',
                  default: 'https://next.stoplight.io',
                  hint: 'Default: https://next.stoplight.io',
                  required: false,
                },
                {
                  name: 'icon',
                  label: 'Icon',
                  widget: 'string',
                  required: false,
                },
                {
                  name: 'download',
                  label: 'Download File',
                  widget: 'string',
                  required: false,
                  hint: 'URL to file to download',
                },
                {
                  name: 'type',
                  label: 'Type',
                  widget: 'select',
                  options: ['link', 'video', 'submit'],
                  default: 'link',
                  required: false,
                },
                {
                  name: 'submit',
                  label: 'Submit',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'button',
                      label: 'Button',
                      widget: 'object',
                      fields: [
                        {
                          name: 'href',
                          label: 'Link',
                          widget: 'string',
                          required: false,
                        },
                        {
                          name: 'title',
                          label: 'Title',
                          widget: 'string',
                          required: false,
                        },
                        {
                          label: 'Color',
                          name: 'color',
                          widget: 'string',
                          default: 'purple',
                          hint: 'Default: purple',
                          required: false,
                        },
                        {
                          name: 'outlined',
                          label: 'Outlined?',
                          widget: 'boolean',
                          required: false,
                        },
                        {
                          name: 'icon',
                          label: 'Icon',
                          widget: 'string',
                          required: false,
                        },
                        {
                          name: 'type',
                          label: 'Type',
                          widget: 'select',
                          options: ['link', 'video'],
                          default: 'link',
                          required: false,
                        },
                      ],
                    },
                    {
                      name: 'input',
                      label: 'Input',
                      widget: 'object',
                      required: false,
                      fields: [
                        {
                          name: 'type',
                          label: 'Type',
                          widget: 'string',
                          default: 'email',
                          required: false,
                        },
                        {
                          name: 'placeholder',
                          label: 'Placeholder',
                          widget: 'string',
                          required: false,
                        },
                      ],
                    },
                    {
                      name: 'formId',
                      label: 'Hubspot FormId',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'outlined',
                  label: 'Outlined?',
                  widget: 'boolean',
                  required: false,
                },
              ],
            },
          ],
        },
        {
          name: 'testimonials',
          label: 'Testimonials',
          widget: 'list',
          required: false,
          fields: [
            {
              name: 'image',
              label: 'image',
              widget: 'image',
            },
            {
              name: 'quote',
              label: 'quote',
              widget: 'string',
            },
            {
              name: 'author',
              label: 'author',
              widget: 'string',
            },
            {
              name: 'company',
              label: 'company',
              widget: 'string',
            },
            {
              name: 'role',
              label: 'role',
              widget: 'string',
            },
          ],
        },
        {
          name: 'cta',
          label: 'Call to action',
          widget: 'object',
          required: false,
          fields: [
            {
              name: 'title',
              label: 'Title',
              widget: 'string',
              hint: 'Leave blank to hide',
              required: false,
            },
            {
              label: 'Color',
              name: 'color',
              widget: 'string',
              default: 'black',
              required: false,
            },
            {
              name: 'href',
              label: 'Link',
              widget: 'string',
              default: 'https://next.stoplight.io',
              hint: 'Default: https://next.stoplight.io',
              required: false,
            },
            {
              name: 'icon',
              label: 'Icon',
              widget: 'string',
              required: false,
            },
            {
              name: 'download',
              label: 'Download File',
              widget: 'string',
              required: false,
              hint: 'URL to file to download',
            },
            {
              name: 'type',
              label: 'Type',
              widget: 'select',
              options: ['link', 'video', 'submit'],
              default: 'link',
              required: false,
            },
            {
              name: 'submit',
              label: 'Submit',
              widget: 'object',
              required: false,
              fields: [
                {
                  name: 'button',
                  label: 'Button',
                  widget: 'object',
                  fields: [
                    {
                      name: 'href',
                      label: 'Link',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: false,
                    },
                    {
                      label: 'Color',
                      name: 'color',
                      widget: 'string',
                      default: 'purple',
                      hint: 'Default: purple',
                      required: false,
                    },
                    {
                      name: 'outlined',
                      label: 'Outlined?',
                      widget: 'boolean',
                      required: false,
                    },
                    {
                      name: 'icon',
                      label: 'Icon',
                      widget: 'string',
                      required: false,
                    },
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'select',
                      options: ['link', 'video'],
                      default: 'link',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'input',
                  label: 'Input',
                  widget: 'object',
                  required: false,
                  fields: [
                    {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'email',
                      required: false,
                    },
                    {
                      name: 'placeholder',
                      label: 'Placeholder',
                      widget: 'string',
                      required: false,
                    },
                  ],
                },
                {
                  name: 'formId',
                  label: 'Hubspot FormId',
                  widget: 'string',
                  required: false,
                },
              ],
            },
            {
              name: 'outlined',
              label: 'Outlined?',
              widget: 'boolean',
              required: false,
            },
          ],
        },
      ],
    },
    {
      label: 'Meta Tags',
      name: 'meta',
      widget: 'object',
      required: false,
      hint: 'Defaults to the meta tags defined in Site Settings',
      fields: [
        {
          label: 'Favicon',
          name: 'favicon',
          widget: 'image',
          required: false,
        },
        {
          name: 'title',
          label: 'Site Name',
          widget: 'string',
          required: false,
        },
        {
          label: 'description',
          name: 'description',
          widget: 'string',
          required: false,
        },
        {
          label: 'URL',
          name: 'url',
          widget: 'string',
          required: false,
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          required: false,
        },
        {
          label: 'Robots',
          name: 'robots',
          widget: 'string',
          default: 'index, follow',
          required: false,
        },
        {
          label: 'Canonical',
          name: 'canonical',
          widget: 'string',
          required: false,
        },
        {
          label: 'Twitter',
          name: 'twitter',
          widget: 'object',
          required: false,
          fields: [
            {
              label: 'Title',
              name: 'title',
              widget: 'string',
              required: false,
            },
            {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: false,
            },
            {
              label: 'Image',
              name: 'image',
              widget: 'image',
              required: false,
            },
            {
              label: 'Username',
              name: 'username',
              widget: 'string',
              required: false,
            },
          ],
        },
      ],
    },
  ],
};
